apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resources-db
  namespace: k8s-program
spec:
  serviceName: resources-db
  replicas: 1
  selector:
    matchLabels:
      app: resources-db
  template:
    metadata:
      labels:
        app: resources-db
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            requests:
              cpu: "500m"
              memory: "1.5Gi"
              ephemeral-storage: "300Mi"
            limits:
              cpu: "2"
              memory: "3Gi"
              ephemeral-storage: "1Gi"
          env:
            - { name: POSTGRES_DB, value: resources }
            - { name: POSTGRES_USER, value: postgres }
            - { name: POSTGRES_PASSWORD, value: postgres }
          volumeMounts:
            - { name: resources-db-data, mountPath: /var/lib/postgresql/data }
  volumeClaimTemplates:
    - metadata:
        name: resources-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: hostpath
        resources:
          requests:
            storage: 1Gi
