apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: song-microservice-persistent-volume-claim
  namespace: microservice-ns
spec:
  # StorageClassName "manual" - a name that can used in PersistentVolume/PersistentVolumeClaim
  # without actually create a StorageClass for it.
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # The volume can be mounted as read-write by a single node.
                    # Must match accessMode in the respective PersistentVolume.
  resources:
    requests:
      storage: 1Gi
