apiVersion: v1
kind: PersistentVolume
metadata:
  name: song-microservice-persistent-volume
  labels:
    type: local
spec:
  # StorageClassName "manual" - a name that can used in PersistentVolume/PersistentVolumeClaim
  # without actually create a StorageClass for it.
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # The volume can be mounted as read-write by a single node.
  hostPath:
    path: "/mnt/persistentVolume/microservice/song" # such path/directory will be created on node
