apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: songs-db
  namespace: k8s-program
spec:
  serviceName: songs-db
  replicas: 1
  selector:
    matchLabels:
      app: songs-db
  template:
    metadata:
      labels:
        app: songs-db
    spec:
      containers:
        - name: postgres-container
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: songs-db
          volumeMounts:
            - name: songs-persistent-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: songs-persistent-storage
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: songs-db-service
  namespace: k8s-program
spec:
  type: ClusterIP
  selector:
    app: songs-db
  ports:
    - port: 5432
      targetPort: 5432