apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-service-deployment
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: songs-service
  template:
    metadata:
      labels:
        app: songs-service
    spec:
      containers:
        - name: songs-service
          image: songs-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SONGS_DB_URL
              value: "songs-db-service"
            - name: SONGS_DB_PORT
              value: "5432"
            - name: SONGS_DB_NAME
              value: "songs-db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"

          volumeMounts: # mount volume to container coming from PVC
            - mountPath: /app/data           # mount path inside the pod container
              name: songs-volume
      volumes:
        - name: songs-volume               # PVC reference name
          persistentVolumeClaim:
            claimName: songs-pvc           # PVC that is mounted to the container
---
apiVersion: v1
kind: Service
metadata:
  name: songs-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: songs-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30002