apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-db
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: songs-db
  template:
    metadata:
      labels:
        app: songs-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          volumeMounts:
            - name: songs-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: songs-storage
          persistentVolumeClaim:
            claimName: songs-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-db
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: resources-db
  template:
    metadata:
      labels:
        app: resources-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: songs-db
  namespace: k8s-program
spec:
  selector:
    app: songs-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: resources-db
  namespace: k8s-program
spec:
  selector:
    app: resources-db
  ports:
    - port: 5432
      targetPort: 5432
