apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-ms
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources-ms
  template:
    metadata:
      labels:
        app: resources-ms
    spec:
      containers:
        - name: resources-ms
          image: resources-ms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: RESOURCES_DB_URL
              value: resources-db-0.resources-db.k8s-program.svc.cluster.local
            - name: RESOURCES_DB_PORT
              value: "5433"
            - name: SONGS_MS_URL
              value: songs-ms
            - name: SONGS_MS_PORT
              value: "8081"
            - name: EUREKA_URI
              value: eureka-server
            - name: ENABLE_EUREKA_CLIENT
              value: "true"
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
