{{- if .Values.resourcesService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: resources
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: resources
    {{- include "microservices-intro-helm.commonLabels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: resources
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.resourcesService.nodePort }}
{{- end }}
