# ============================
#  Global configuration
# ============================
global:
  namespace: k8s-program


# ============================
#  Microservices configuration
# ============================
resourcesService:
  enabled: true
  replicaCount: 2
  image: "resources-service:1.0"
  nodePort: 30080

songsService:
  enabled: true
  replicaCount: 2
  image: "songs-service:1.1"
  nodePort: 30081


# ============================
#  PostgreSQL databases
# ============================
postgres:
  resourcesDb:
    enabled: true
    image: "postgres:15-alpine"

  songsDb:
    enabled: true
    image: "postgres:15-alpine"


# ============================
#  Songs persistence
# ============================
persistence:
  songs:
    enabled: true
    storageClassName: hostpath
    size: 1Gi


# ============================
#  StorageClass configuration
# ============================
storageClass:
  create: true              # <== toggle this when deploying to multiple namespaces
  name: hostpath
  provisioner: rancher.io/local-path
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
