apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-microservice-with-statefulset-deployment
  namespace: microservice-with-statefulset-ns
  labels:
    app: song-microservice-with-statefulset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song-microservice-with-statefulset
  template:
    metadata:
      labels:
        app: song-microservice-with-statefulset
    spec:
      containers:
        - name: song-microservice-with-statefulset
          image: experimentalmicroservice-1-songs-ms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-statefulset-secret
                  key: postgres-root-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-statefulset-secret
                  key: postgres-root-password
            - name: SONGS_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: experimental-service-db-statefulset-config
                  key: song_database_url
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: experimental-service-db-statefulset-config
                  key: database_name
---
apiVersion: v1
kind: Service
metadata:
  name: song-microservice-with-statefulset-service
  namespace: microservice-with-statefulset-ns
spec:
  type: NodePort
  selector:
    app: song-microservice-with-statefulset
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-microservice-with-statefulset-deployment
  namespace: microservice-with-statefulset-ns
  labels:
    app: resource-microservice-with-statefulset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource-microservice-with-statefulset
  template:
    metadata:
      labels:
        app: resource-microservice-with-statefulset
    spec:
      containers:
        - name: resource-microservice-with-statefulset
          image: experimentalmicroservice-1-resources-ms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-statefulset-secret
                  key: postgres-root-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-statefulset-secret
                  key: postgres-root-password
            - name: RESOURCES_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: experimental-service-db-statefulset-config
                  key: resource_database_url
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: experimental-service-db-statefulset-config
                  key: database_name
---
apiVersion: v1
kind: Service
metadata:
  name: resource-microservice-with-statefulset-service
  namespace: microservice-with-statefulset-ns
spec:
  type: NodePort
  selector:
    app: resource-microservice-with-statefulset
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 30002
