apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-pvc
  namespace: k8s-program
  labels:
    app: songs
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeName: songs-pv
