apiVersion: v1
kind: PersistentVolume
metadata:
  name: songs-pv
  labels:
    app: songs
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/k8s/songs-data
