apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-ms-dpl
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources-ms-dpl
  template:
    metadata:
      labels:
        app: resources-ms-dpl
    spec:
      containers:
        - name: resources-service
          image: resources-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          env:
            - name: RESOURCES_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: resources-ms-config-cm
                  key: RESOURCES_DB_URL
            - name: RESOURCES_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: resources-ms-config-cm
                  key: RESOURCES_DB_PORT
            - name: SONGS_MS_URL
              valueFrom:
                configMapKeyRef:
                  name: resources-ms-config-cm
                  key: SONGS_MS_URL
            - name: SONGS_MS_PORT
              valueFrom:
                configMapKeyRef:
                  name: resources-ms-config-cm
                  key: SONGS_MS_PORT
