apiVersion: v1
kind: ConfigMap
metadata:
  name: resources-initdb-cm
  namespace: k8s-program
data:
  resources_initdb_sql: |
    drop table if exists resources cascade;
    create table resources (
      id serial not null,
      blob bytea,
      primary key (id)
    );
