apiVersion: v1
kind: ConfigMap
metadata:
  name: songs-ms-config-cm
  namespace: k8s-program
data:
  resources_db_url: "resources-db-svc"
  resources_db_port: "5432"
  songs_ms_url: "songs-ms-svc"
  songs_ms_port: "8081"
