apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: songs-db-sts
  namespace: k8s-program
spec:
  serviceName: songs-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: songs-db-sts
  template:
    metadata:
      labels:
        app: songs-db-sts
    spec:
      containers:
        - name: songs-db
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d postgres
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d postgres
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d postgres
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-config-scr
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-config-scr
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config-cm
                  key: postgres_db
          volumeMounts:
            - name: songs-data
              mountPath: /var/lib/postgresql/data
            - name: songs-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: songs-initdb
          configMap:
            name: songs-initdb-cm
            items:
              - key: songs_initdb.sql
                path: songs_initdb.sql
  volumeClaimTemplates:
    - metadata:
        name: songs-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: hostpath
        resources:
          requests:
            storage: 300Mi
