apiVersion: v1
kind: Secret
metadata:
  name: resources-db-credentials
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "microservices-intro-helm.commonLabels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: c2VjcmV0LWFkbWlu
  POSTGRES_PASSWORD: c29tZS1zZWNyZXQtcGFzc3dvcmQjMTIz
