apiVersion: v1
kind: Secret
metadata:
  name: songs-db-credentials
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "microservices-intro-helm.commonLabels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: c2VjcmV0LXVzZXI=
  POSTGRES_PASSWORD: dmVyeS1zZWNyZXQtcGFzc3dvcmRANDU2
