apiVersion: v1
kind: ConfigMap
metadata:
  name: songs-config
  namespace: k8s-program
data:
  SONGS_MS_NAME: "songs-ms"
  SONGS_MS_PORT: "8081"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://songs-db:5432/songs"
