apiVersion: v1
kind: ConfigMap
metadata:
  name: songs-db-init-sql
  namespace: k8s-program
data:
  01_songs.sql: |
    -- Table: songs
    CREATE TABLE IF NOT EXISTS songs (
        id SERIAL PRIMARY KEY,
        name TEXT,
        artist TEXT,
        album TEXT,
        genre TEXT,
        length TEXT,
        resource_id INTEGER UNIQUE NOT NULL,
        year TEXT
    );
