apiVersion: v1
kind: ConfigMap
metadata:
  name: resources-db-init-sql
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "microservices-intro-helm.commonLabels" . | nindent 4 }}
data:
  01_resources.sql: |
    -- Table: resources
    CREATE TABLE IF NOT EXISTS resources (
        id SERIAL PRIMARY KEY,
        blob BYTEA
    );
