apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-microservice-deployment
  namespace: microservice-ns
  labels:
    app: song-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song-microservice
  template:
    metadata:
      labels:
        app: song-microservice
    spec:
      volumes:
        - name: song-microservice-storage # A Reference to the respective persistence vo;ume claim.
          persistentVolumeClaim:
            claimName: song-microservice-persistent-volume-claim
      containers:
        - name: song-microservice
          image: experimentalmicroservice-1-songs-ms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: postgres-root-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: postgres-root-password
            - name: SONGS_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: experimental-service-db-config
                  key: song_database_url
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: experimental-service-db-config
                  key: database_name
          volumeMounts:
            - mountPath: "/persistentVolume/microservice/song" # A path that is mounted to this container.
              # This path may vary from the path defined in the PersistentVolumeConfig
              name: song-microservice-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-microservice-deployment
  namespace: microservice-ns
  labels:
    app: resource-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource-microservice
  template:
    metadata:
      labels:
        app: resource-microservice
    spec:
      containers:
        - name: resource-microservice
          image: experimentalmicroservice-1-resources-ms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: postgres-root-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: postgres-root-password
            - name: RESOURCES_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: experimental-service-db-config
                  key: resource_database_url
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: experimental-service-db-config
                  key: database_name
