{{- if .Values.persistence.songs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-pvc
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: songs
    {{- include "microservices-intro-helm.commonLabels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.persistence.songs.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.songs.size | quote }}
{{- end }}
