{{- if .Values.songsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: songs
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: songs
    {{- include "microservices-intro-helm.commonLabels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: songs
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: {{ .Values.songsService.nodePort }}
{{- end }}
