apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-deployment
  labels:
    app: resources
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources
  template:
    metadata:
      name: resources
      labels:
        app: resources
      namespace: microservices
    spec:
      containers:
        - name: resources
          image: resources-image:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: RESOURCES_DB_URL
              value: "resources-db-service"
            - name: RESOURCES_DB_PORT
              value: "5432"
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
