{{ $root := . }}
{{ range $key, $app := .Values.apps}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "serviceName" (include "dbName" $key) }}
  namespace: {{ required "namespace is required!" $root.Values.namespace }}
spec:
  selector:
    app: {{ include "dbName" $key }}
  type: ClusterIP
  ports:
    - port: {{ $app.db.servicePort }}
      targetPort: {{ $app.db.containerPort }}
---
{{ end -}}
