{{ $root := . }}
{{ range $key, $app := .Values.apps }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dbName" $key }}
  namespace: {{ required "namespace is required!" $root.Values.namespace }}
spec:
  replicas: {{ $app.db.replicas }}
  selector:
    matchLabels:
      app: {{ include "dbName" $key }}
  serviceName: {{ include "serviceName" (include "dbName" $key) }}
  template:
    metadata:
      labels:
        app: {{ include "dbName" $key }}
    spec:
      containers:
        - name: {{ include "dbName" $key }}
          image: {{ printf "%s:%s" $app.db.imageName $app.db.imageTag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $root.Values.secrets.db.name }}
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $root.Values.secrets.db.name }}
                  key: postgres_pass
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ $root.Values.configs.db.name }}
                  key: db
          volumeMounts:
            - mountPath: /data
              name: data
            - name: db-init
              mountPath: /docker-entrypoint-initdb.d
          ports:
            - containerPort: {{ $app.db.containerPort }}
              protocol: TCP
{{ include "dbProbes" $app | indent 10 }}
      volumes:
        - name: db-init
          configMap:
            name: {{ $root.Values.configs.app.name }}
            items:
              - key: {{ printf "%s_init.sql" $key }}
                path: {{ printf "%s_init.sql" $key }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
---
{{ end }}