{{ $root := . }}
{{ range $key, $app := .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-deployment" $key }}
  labels:
    app: {{ $key }}
  namespace: {{ required "namespace is required!" $root.Values.namespace }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  replicas: {{ $app.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      name: {{ $key }}
      labels:
        app: {{ $key }}
      namespace: {{ required "namespace is required!" $root.Values.namespace }}
    spec:
      containers:
        - name: {{ $key }}
          image: {{ printf "%s:%s" $app.deployment.imageName $app.deployment.imageTag }}
          imagePullPolicy: IfNotPresent
          env:
            {{- if eq $key "songs" }}
            - name: SONGS_DB_URL
              value: songs-db-service
            {{- else if eq $key "resources" }}
            - name: RESOURCES_DB_URL
              value: "resources-db-service"
            - name: RESOURCES_DB_PORT
              value: "5432"
            {{- end }}
          ports:
            - containerPort: {{ $app.deployment.port }}
              protocol: TCP
          {{- if eq $key "songs" }}
          volumeMounts:
            - mountPath: /data
              name: data
          {{- end }}
{{ include "containerProbes" $app | indent 10 }}
      {{- if eq $key "songs" }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ printf "%s-pvc" $key }}
      {{- end }}
      restartPolicy: Always
---
{{ end }}
