{{ $root := . }}
{{ range $key, $app := .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "serviceName" $key }}
  namespace: {{ required "namespace is required!" $root.Values.namespace }}
spec:
  selector:
    app: {{ $key }}
  ports:
    - protocol: TCP
      port: {{ $app.service.port }}
      targetPort: {{ $app.deployment.port }}
      nodePort: {{ $app.service.nodePort }}
  type: NodePort
---
{{ end }}
