apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: songs
  template:
    metadata:
      labels:
        app: songs
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
      containers:
        - name: songs
          image: songs-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
              ephemeral-storage: "300Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
              ephemeral-storage: "1Gi"
          env:
            - {
              name: JAVA_TOOL_OPTIONS,
              value: "-XX:InitialRAMPercentage=35 -XX:MaxRAMPercentage=70 -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError",
            }
            - { name: SONGS_MS_NAME, value: "songs-ms" }
            - { name: SONGS_MS_PORT, value: "8081" }
            - { name: ENABLE_EUREKA_CLIENT, value: "false" }
            - {
              name: SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED,
              value: "false",
            }
            - { name: EUREKA_CLIENT_REGISTER_WITH_EUREKA, value: "false" }
            - { name: EUREKA_CLIENT_FETCH_REGISTRY, value: "false" }
            - {
              name: SPRING_DATASOURCE_URL,
              value: "jdbc:postgresql://songs-db:5432/songs",
            }
            - { name: SPRING_DATASOURCE_USERNAME, value: "postgres" }
            - { name: SPRING_DATASOURCE_PASSWORD, value: "postgres" }
            - { name: SPRING_JPA_HIBERNATE_DDL_AUTO, value: "update" }
            - { name: SPRING_JPA_SHOW_SQL, value: "true" }
            - {
              name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL,
              value: "true",
            }
          volumeMounts:
            - name: songs-volume
              mountPath: /data/songs
      volumes:
        - name: songs-volume
          persistentVolumeClaim:
            claimName: songs-pvc
