apiVersion: apps/v1
kind: Deployment
metadata:
  name: experimental-songs-service-db-deployment
  namespace: database-ns
  labels:
    app: song-postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-postgres-db
  template:
    metadata:
      labels:
        app: song-postgres-db
    spec:
      containers:
      - name: song-postgres-db
        image: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: postgres-root-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: postgres-root-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: experimental-service-db-config
              key: database_name
---
apiVersion: v1
kind: Service
metadata:
  name: song-postgres-db-service
  namespace: database-ns
spec:
  selector:
    app: song-postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: experimental-resources-service-db-deployment
  namespace: database-ns
  labels:
    app: resources-postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resources-postgres-db
  template:
    metadata:
      labels:
        app: resources-postgres-db
    spec:
      containers:
        - name: resources-postgres-db
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: postgres-root-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: postgres-root-password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: experimental-service-db-config
                  key: database_name
---
apiVersion: v1
kind: Service
metadata:
  name: resources-postgres-db-service
  namespace: database-ns
spec:
  selector:
    app: resources-postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
