apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ing
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2$3
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/v1/(resources)(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: resources-ms-svc
                port:
                  number: 8080
          - path: /api/v1/(songs)(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: songs-ms-svc
                port:
                  number: 8081
