apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-ms-dpl
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.resources_ms_dpl.replicas }}
  selector:
    matchLabels:
      app: resources-ms-dpl
  template:
    metadata:
      labels:
        app: resources-ms-dpl
    spec:
      containers:
        - name: resources-service
          image: resources-service:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          {{- include "probes.actuator" 8080 | nindent 10 }}
          env:
            - name: RESOURCES_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: resources-ms-config-cm
                  key: RESOURCES_DB_URL
            - name: RESOURCES_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: resources-ms-config-cm
                  key: RESOURCES_DB_PORT
            - name: SONGS_MS_URL
              valueFrom:
                configMapKeyRef:
                  name: resources-ms-config-cm
                  key: SONGS_MS_URL
            - name: SONGS_MS_PORT
              valueFrom:
                configMapKeyRef:
                  name: resources-ms-config-cm
                  key: SONGS_MS_PORT
