apiVersion: v1
kind: ConfigMap
metadata:
  name: resources-ms-config-cm
  namespace: {{ .Values.namespace }}
data:
  RESOURCES_DB_URL: "resources-db-svc"
  RESOURCES_DB_PORT: "5432"
  SONGS_MS_URL: "songs-ms-svc"
  SONGS_MS_PORT: "8081"
