apiVersion: v1
kind: Service
metadata:
  name: resources-db-svc
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: resources-db-sts
  ports:
    - port: 5432
      targetPort: 5432
