apiVersion: v1
kind: Service
metadata:
  name: resources-ms-svc
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: resources-ms-dpl
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
