apiVersion: v1
kind: Service
metadata:
  name: songs-db-svc
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: songs-db-sts
  ports:
    - port: 5432
      targetPort: 5432
