apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-ms-dpl
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/change-cause: "add the genre column to the songs table"
spec:
  replicas: {{ .Values.songs_ms_dpl.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: songs-ms-dpl
  template:
    metadata:
      labels:
        app: songs-ms-dpl
    spec:
      containers:
        - name: songs-service
          image: songs-service:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          env:
            - name: SONGS_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: songs-ms-config-cm
                  key: SONGS_DB_URL
            - name: SONGS_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: songs-ms-config-cm
                  key: SONGS_DB_PORT
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: songs-pvc
