{{- if .Values.postgres.songsDb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: songs-db
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: songs-db
    {{- include "microservices-intro-helm.commonLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: songs-db
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}
