apiVersion: v1
kind: PersistentVolume
metadata:
  name: resources-db-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/var/lib/postgresql/resources" # Path inside the Minikube VM
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: songs-db-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/var/lib/postgresql/songs" # Path inside the Minikube VM

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-pvc
  namespace: k8s-program
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resources-pvc
  namespace: k8s-program
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: manual