apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resources-db
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resources-db
  serviceName: resources-db-service
  template:
    metadata:
      labels:
        app: resources-db
    spec:
      containers:
        - name: resources-db
          image: postgres:13.20-alpine3.21
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: postgres_pass
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db
          volumeMounts:
            - mountPath: /data
              name: data
            - name: db-init
              mountPath: /docker-entrypoint-initdb.d
          ports:
            - containerPort: 5432
              protocol: TCP
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d postgres
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
              exec:
                command:
                  - sh
                  - -c
                  - pg_isready -U postgres -d postgres
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
          readinessProbe:
              exec:
                command:
                  - sh
                  - -c
                  - pg_isready -U postgres -d postgres
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 5
              failureThreshold: 3
      volumes:
        - name: db-init
          configMap:
            name: app-config
            items:
              - key: resources_init.sql
                path: resources_init.sql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
