apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-deployment
  labels:
    app: songs
  namespace: microservices
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  replicas: 2
  selector:
    matchLabels:
      app: songs
  template:
    metadata:
      name: songs
      labels:
        app: songs
      namespace: microservices
    spec:
      containers:
        - name: songs
          image: songs-image:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: SONGS_DB_URL
              value: songs-db-service
          ports:
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: data
          startupProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            failureThreshold: 30
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/liveness
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/readiness
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: songs-pvc
      restartPolicy: Always
      