apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-pvc
  namespace: microservices
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi