apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resources-db
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resources-db
  serviceName: resources-db-service
  template:
    metadata:
      labels:
        app: resources-db
    spec:
      containers:
        - name: resources-db
          image: postgres:13.20-alpine3.21
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: data
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
          ports:
            - containerPort: 5432
              protocol: TCP
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
