apiVersion: v1
kind: Service
metadata:
  name: resources-service
  namespace: microservices
spec:
  selector:
    app: resources
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
