apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-deployment
  labels:
    app: songs
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: songs
  template:
    metadata:
      name: songs
      labels:
        app: songs
      namespace: microservices
    spec:
      containers:
        - name: songs
          image: songs-image:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SONGS_DB_URL
              value: songs-db-service
          ports:
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: songs-pvc
      restartPolicy: Always
      